h1 .smaller {
    font-size: 0.5em;
}
h2 .smaller {
    font-size: 0.8em;
}
.ods-box {
    border-radius: 0px;
}
.titre {
    border-bottom: 1px solid black;
    width: 100%;
}
/* BOX */
.box {
    padding-left: 3px;
    padding-right: 3px;
}
.grey-box {
    background: #eee;
    border-radius: 0;
    padding: 20px;
    margin-bottom: 6px;
    height: 418px;
}
.grey-box.half-box {
    height: 206px;
}
/* BOX CONTENT */
.title {
    font-size: 1em;
    margin: 0 auto;
}
.description {
    margin: 0 auto;
    color: grey;
    font-size: 0.7em;
    font-weight: 100;
}
.kpi {
    font-size: 1.66em;
    margin-top: 40px;
    font-weight: 500;
    text-align: center;
}
/* BOX Title Line */
h2.grey-box {
    height: 70px;
    font-size: 1.3em;
}
/* CHARTS */
.ods-chart {
    height: 350px;
}
.odswidget-charts {
    margin-top: 10px;
}
.odswidget-table {
    height: 338px;
    margin-top: 10px;
}
rect.highcharts-background {
    fill: #eee !important;
}
tspan.highcharts-text-outline {
    display: none;
}
      
