<section>
    <div class="container">
        <div class="grid sm:grid-2 md:grid-4 gap-10">
            <div class="cell-1 box white flat">
                <div class="advanced-kpi">
                    <div class="advanced-kpi--top">
                        <h3 class="title">
                            Title
                        </h3>
                        <p class="description">
                            Description
                        </p>
                    </div>
                    <div class="advanced-kpi--middle centered">
                        <p class="value">
                            1'234 %
                        </p>
                        <p class="description">
                        </p>
                    </div>
                    <div class="advanced-kpi--bottom">
                        <div class="advanced-kpi--bottom-second-stage">
                            <span class="date">Date</span>
                            <a class="source"
                               href="#"
                               title="Title">
                                Source <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cell-1 box white flat">
                <div class="advanced-kpi">
                    <div class="advanced-kpi--top">
                        <h3 class="title">
                            Title
                        </h3>
                        <p class="description">
                            Description
                        </p>
                    </div>
                    <div class="advanced-kpi--middle centered">
                        <p class="value">
                            1'234 %
                        </p>
                    </div>
                    <div class="advanced-kpi--bottom">
                        <div class="advanced-kpi--bottom-second-stage">
                            <span class="date">Date</span>
                            <a class="source"
                               href="#"
                               title="Title">
                                Source <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cell-1 box white flat">
                <div class="advanced-kpi">
                    <div class="advanced-kpi--top">
                        <h3 class="title">
                            Title
                        </h3>
                        <p class="description">
                            Description
                        </p>
                    </div>
                    <div class="advanced-kpi--middle centered">
                        <p class="value">
                            1'234 %
                        </p>
                    </div>
                    <div class="advanced-kpi--bottom">
                        <div class="advanced-kpi--bottom-second-stage">
                            <span class="date">Date</span>
                            <a class="source"
                               href="#"
                               title="Title">
                                Source <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cell-1 box white flat">
                <div class="advanced-kpi">
                    <div class="advanced-kpi--top">
                        <h3 class="title">
                            Title
                        </h3>
                        <p class="description">
                            Description
                        </p>
                    </div>
                    <div class="advanced-kpi--middle centered">
                        <p class="value">
                            1'234 %
                        </p>
                    </div>
                    <div class="advanced-kpi--bottom">
                        <div class="advanced-kpi--bottom-second-stage">
                            <span class="date">Date</span>
                            <a class="source"
                               href="#"
                               title="Title">
                                Source <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>