<div class="row">
    <div class="col-md-4">
        <!-- Image card. Replace the href to link the card to something useful -->
        <a href="#"
           class="image-card image-card-mobility">
            <div class="image-content">
                <h3 class="image-title">
                    Mobility
                </h3>
                <p class="image-description">
                    Quam vulputate dignissim suspendisse in est ante in nibh. Faucibus nisl tincidunt eget nullam non nisi est sit amet.
                </p>
            </div>
        </a>
    </div>
    <div class="col-md-4">
        <!-- Image card. Replace the href to link the card to something useful -->
        <a href="#"
           class="image-card image-card-garden">
            <div class="image-content">
                <h3 class="image-title">
                    Garden
                </h3>
                <p class="image-description">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
            </div>
        </a>
    </div>
    <div class="col-md-4">
        <!-- Image card. Replace the href to link the card to something useful -->
        <a href="#"
           class="image-card image-card-gastronomy">
            <div class="image-content">
                <h3 class="image-title">
                    Gastronomy
                </h3>
                <p class="image-description">
                    Massa id neque aliquam vestibulum. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate.
                </p>
            </div>
        </a>
    </div>
    <div class="col-md-4">
        <!-- Image card -->
        <a href="#"
           class="image-card image-card-sport">
            <div class="image-content">
                <h3 class="image-title">
                    Sport
                </h3>
                <p class="image-description">
                    Sed augue lacus viverra vitae congue. Neque egestas congue quisque egestas diam in arcu.
                </p>
            </div>
        </a>
    </div>
    <div class="col-md-4">
        <!-- Image card -->
        <a href="#"
           class="image-card image-card-culture">
            <div class="image-content">
                <h3 class="image-title">
                    Culture
                </h3>
                <p class="image-description">
                    Integer malesuada nunc vel risus commodo viverra maecenas. Sem et tortor consequat id porta.
                </p>
            </div>
        </a>
    </div>
    <div class="col-md-4">
        <!-- Image card -->
        <a href="#"
           class="image-card image-card-education">
            <div class="image-content">
                <h3 class="image-title">
                    Education
                </h3>
                <p class="image-description">
                    Euismod lacinia at quis risus sed vulputate odio. Parturient montes nascetur ridiculus mus mauris vitae.
                </p>
            </div>
        </a>
    </div>
</div>
