<section>
    <div class="container">
        <div class="heading">
            <h1>Title</h1>
            <h2>Sub title</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam atque commodi cupiditate, deserunt
                dolores dolorum ducimus ea fugiat non quidem repellat soluta voluptate voluptatem. Illo illum maxime
                nemo officia velit.</p>
        </div>
        <div class="grid-2 gap-1">
            <div class="sm:cell-1 content-box text align-right">
                <h3>Title</h3>
                <h4>Subtitle</h4>
                <p>Aligned text on the right</p>
            </div>
            <div class="sm:cell-1 content-box">
                Chart here
            </div>
        </div>
        <div class="content-box text">
            <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam atque commodi cupiditate, deserunt
                dolores dolorum ducimus ea fugiat non quidem repellat soluta voluptate voluptatem. Illo illum maxime
                nemo officia velit.</p>
        </div>
        <div class="grid-2 gap-1">
            <div class="sm:cell-1 sm:cell-order-2 content-box text align-left">
                <h3>Title</h3>
                <h4>Subtitle</h4>
                <p>Aligned text on the left</p>
            </div>
            <div class="sm:cell-1 sm:cell-order-1 content-box">
                Chart here
            </div>
        </div>
    </div>
</section>