/* Dropdown menu with pill styling
   ========================================================================== */
/* Button */
.button {
    font-size: 1rem;
    color: var(--text);
    border: 1px solid #cbd2db;
    border-radius: 2rem;
    background: #FFFFFF;
    padding: .37rem 1rem;
    margin-right: 6px;
    transition: all .2s;
}
.button:hover{
    color: var(--links);
    border-color: var(--links);
}
.button-active {
   background-color: var(--links);
   color: #FFF;
}

.button-active:hover {
   background: #FFFFFF;
    color: var(--text);
}
