<div class="container row">
    <div class="col-md-3">
        <div class="contact-card">
            <div class="contact-card-header">
                <img class="contact-card-photo"
                     src="https://discovery.opendatasoft.com/assets/theme_image/contact-card-avatar-woman.svg">
                <div class="contact-card-tag">
                    R&amp;D
                </div>
            </div>
            <h2 class="contact-card-title">
                Ines Blanchet
            </h2>
            <h3 class="contact-card-post">
                Ingénieure Chimiste
            </h3>
            <h4 class="contact-card-description">
                Paris - France
                <br>
                01 23 45 67 89
                <br>
                mail@mail.com
            </h4>
        </div>
    </div>
</div>
