<div class="container">
    <h1 class="mb-2">
        Section
    </h1>
    <div class="row">
        <div class="col-md-4">
            <div class="box white flat">
                <div class="advanced-kpi">
                    <div class="advanced-kpi--top">
                        <h3 class="title">
                            KPI
                        </h3>
                        <p class="description">
                            sub titile
                        </p>
                    </div>
                    <div class="advanced-kpi--middle centered">
                        <p class="value">
                            123
                        </p>
                    </div>
                    <div class="advanced-kpi--bottom">
                        <div>Additional info</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="box white flat">
                <div class="advanced-kpi">
                    <div class="advanced-kpi--top">
                        <h3 class="title">
                            KPI
                        </h3>
                        <p class="description">
                            sub title
                        </p>
                    </div>
                    <div class="advanced-kpi--middle centered">
                        <p class="value">
                            456
                        </p>
                    </div>
                    <div class="advanced-kpi--bottom">
                        <div>Additional info</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="box white flat">
                <div class="advanced-kpi">
                    <div class="advanced-kpi--top">
                        <h3 class="title">
                            KPI
                        </h3>
                        <p class="description">
                            sub title
                        </p>
                    </div>
                    <div class="advanced-kpi--middle centered">
                        <p class="value">
                            789
                        </p>
                    </div>
                    <div class="advanced-kpi--bottom">
                        <div>Additional info</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h2 class="mb-2">
        Section
    </h2>
    <div class="row">
        <div class="col-md-4">
            <div class="row full-height">
                <div class="col-md-12">
                    <div class="box white flat">
                        <div class="advanced-kpi">
                            <div class="advanced-kpi--top">
                                <h3 class="title">
                                    KPI
                                </h3>
                                <p class="description">
                                    sub title
                                </p>
                            </div>
                            <div class="advanced-kpi--middle centered">
                                <p class="value">
                                    A'B'C
                                </p>
                            </div>
                            <div class="advanced-kpi--bottom">
                                <div>Additional info</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 no-mb">
                    <div class="box white flat">
                        <div class="advanced-kpi">
                            <div class="advanced-kpi--top">
                                <h3 class="title">
                                    KPI
                                </h3>
                                <p class="description">
                                    sub title
                                </p>
                            </div>
                            <div class="advanced-kpi--middle centered">
                                <p class="value">
                                    X'Y'Z
                                </p>
                            </div>
                            <div class="advanced-kpi--bottom">
                                <div>Additional info</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="box white flat">
                <div class="advanced-kpi">
                    <div class="advanced-kpi--top">
                        <h3 class="title">
                            CHART
                        </h3>
                        <p class="description">
                            sub title
                        </p>
                    </div>
                    <div class="advanced-kpi--middle no-bg mb-0">
                        <div style="height:300px">
                        </div>
                    </div>
                    <div class="advanced-kpi--bottom">
                        <div>Additional info</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>