h1 .smaller {
    font-size: 0.5em;
}
h2 .smaller {
    font-size: 0.8em;
}
.ods-box {
    border-radius: 0px;
}
.titre {
    border-bottom: 1px solid black;
    width: 264px;
}
/* SEARCH */
.odswidget-text-search__search-box {
    font-size: 1.0rem;
    padding-top: 4px;
    padding-bottom: 3px;
}
.recherche {
    margin-bottom: 20px;
}
/* TABS */
.items {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    margin-bottom: -8px;
}
.item {
    margin: 0px 15px 8px 0px;
    border-radius: 0px;
    font-size: 1.2em;
    padding: 1px 5px;
    font-family: 'Oswald', "Open Sans", Helvetica, arial, sans-serif;
    font-weight: 100;
    color: #666666;
    border-left: 1px solid #666;
    border-bottom: 1px solid #666;
}
.item:hover {
    border-left: 2px solid #ec643c;
    border-bottom: 2px solid #ec643c;
    padding-left: 4px;
}
.item_selected, .item_selected:hover {
    border-left: 2px solid black;
    border-bottom: 2px solid black;
    color: black;
    padding-left: 5px;
}
.ods-tabs__tab {
    color: black;
}
/* BOX */
.box {
    padding-left: 3px;
    padding-right: 3px;
}
.grey-box {
    background: #eee;
    border-radius: 0;
    padding: 20px;
    margin-bottom: 6px;
    height: 418px;
}
.grey-box.half-box {
    height: 206px;
}
/* BOX CONTENT */
.title {
    font-size: 1em;
    margin: 0 auto;
}
.description {
    margin: 0 auto;
    color: grey;
    font-size: 0.7em;
    font-weight: 100;
}
.kpi {
    font-size: 1.66em;
    margin-top: 40px;
    font-weight: 500;
    text-align: center;
}
/* BOX Title Line */
h2.grey-box {
    height: 70px;
    font-size: 1.3em;
}
/* CHARTS */
.ods-chart {
    height: 350px;
}
.odswidget-charts {
    margin-top: 10px;
}
.odswidget-table {
    height: 338px;
    margin-top: 10px;
}
rect.highcharts-background {
    fill: #eee !important;
}
