.map-container {
    position: relative;
}
/* inlined legend */
.odswidget-map-legend__choropleth-container {
    display: flex;
    justify-content: space-evenly;
}
.odswidget.odswidget-map-legend {
    left: 4px;
    right: 4px;
    width: inherit;
    padding: 5px 5px 0 5px;
    background-color: #ffffffd1;
}
.odswidget-map-legend__choropleth__item {
    flex-direction: column;
    align-items: center;
}
.odswidget-map-legend__choropleth__item-color {
    margin: 0;
}
.odswidget-map-legend__choropleth__color-block {
    width: 120px;
}
i.fa.fa-long-arrow-right.odswidget-map-legend__choropleth__item-range__bound-arrow {
    margin: 10px;
}
.odswidget-map-legend__choropleth__item-range__bound {
    width: inherit;
}
.odswidget-map-legend__choropleth__item-range {
    font-size: inherit;
    align-items: center;
}
.leaflet-bottom.leaflet-left {
    bottom: 130px;
}
      
