<div class="row">
    <div class="col-md-4">
        <a href="#" class="access-card-bg"
           style="background-image: url('https://userclub.opendatasoft.com/assets/theme_image/access-cards.jpg')">
            <div class="access-card">
                <div class="access-card-content">
                    <h3 class="access-card-pretitle">Éphémère</h3>
                    <h2 class="access-card-title">Opération jardins éphémères</h2>
                    <h4 class="access-card-subtitle">
                        Liste et carte des jardins éphémères 2021
                    </h4>
                    <div class="access-card-description">
                        <h4>Catégories</h4>
                        <p>Politique publique : Biodiversité</p>
                        <p>Type : Catalogue</p>
                        <p>Support : Portail opendata</p>
                        <p>Développement : Direction du Numérique - Orléans Métropole</p>
                    </div>
                </div>
                <div class="access-card-button">
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                </div>
            </div>
        </a>
    </div>
</div>