main.main--page {
    margin: 0;
}

.justify-text {
    text-align: justify;
}

.center-text {
    text-align: center;
}

.header-title {
    text-align: center;
    font-size: 4rem;
    font-weight: normal;
    margin-bottom: 0;
    color: var(--highlight);
}

.header-subtitle {
    font-size: 1.7rem;
    text-align: center;
    margin: 0;
    font-weight: normal;
}

.block-section {
    margin: 26px 0px;
}

.block-white {
    padding: 65px 0;
    background-color: #FFFFFF;
}

.block-grey {
    padding: 65px 0;
    background-color: #f7f8f8;
}

.block-title {
    font-size: 2.2rem;
    text-align: center;
    font-weight: 500;
    color: var(--highlight);
    margin-bottom: .5rem;
}

.block-subtitle {
    font-size: 1.44rem;
    font-weight: normal;
    margin-top: 0;
    margin-bottom: 2rem;
    text-align: center;
    color: var(--titles);
}

.block-text {
    font-size: 1.2rem;
    margin-bottom: 1.5rem;
    line-height: 1.7;
}

rect.highcharts-background {
    fill: rgba(0, 0, 0, 0) !important;
}
      