<div class="kpi-card">
    <ods-simple-tabs class="tab-dots">
        <ods-simple-tab keep-content="true">
            <i class="kpi-icon fa fa-gitlab" aria-hidden="true"></i>
            <h2 class="kpi-title">
                5,983
            </h2>
            <p class="kpi-description">
                Dignissim suspendisse in est ante in nibh nisl tincidunt eget
            </p>
        </ods-simple-tab>
        <ods-simple-tab keep-content="true">
            <i class="kpi-icon fa fa-houzz" aria-hidden="true"></i>
            <h2 class="kpi-title">
                18.3k
            </h2>
            <p class="kpi-description">
                Quam vulputate dignissim suspendisse in est ante in nibh. Faucibus nisl tincidunt eget nullam non nisi est sit amet
            </p>
        </ods-simple-tab>
        <ods-simple-tab keep-content="true">
            <i class="kpi-icon fa fa-houzz" aria-hidden="true"></i>
            <h2 class="kpi-title">
                8.3k
            </h2>
            <p class="kpi-description">
                Quam vulputate
            </p>
        </ods-simple-tab>
    </ods-simple-tabs>
</div>
      