<div class="container">
    <h4>Spanning rows</h4>
    <div class="grid-4 grid-rows-2">
        <div class="cell-1 cell-row-span-2 box dark">1</div>
        <div class="cell-3 box dark">2</div>
        <div class="cell-3 box dark">3</div>
    </div>

    <h4>Last cell (4) fill the gap</h4>
    <div class="grid-4 grid-rows-3">
        <div class="cell-1 cell-row-3 box dark">1</div>
        <div class="cell-2 box dark">2</div>
        <div class="cell-1 cell-row-3 box dark">3</div>
        <div class="cell-2 cell-row-2 box dark">4</div>
    </div>
</div>