<div class="container">
    <h4>Spanning</h4>
    <div class="grid-cols-3">
        <div class="box dark">1</div>
        <div class="box dark">2</div>
        <div class="box dark">3</div>
        <div class="cell-span-2 box dark">4</div>
        <div class="box dark">5</div>
        <div class="box dark">6</div>
        <div class="cell-span-2 box dark">7</div>
    </div>

    <h4>Positioning</h4>
    <div class="grid-cols-6">
        <div class="cell-start-2 cell-span-4 box dark">1</div>
        <div class="cell-start-1 cell-end-3 box dark">2</div>
        <div class="cell-end-7 cell-span-2 box dark">3</div>
        <div class="cell-start-1 cell-end-7 box dark">4</div>
    </div>
</div>