#c1 .odswidget-date-range-slider .irs--flat .irs-handle>i:first-child,
#c1 .odswidget-date-range-slider .irs--flat .irs-bar,
#c1 .odswidget-date-range-slider .irs--flat .irs-from,
#c1 .odswidget-date-range-slider .irs--flat .irs-to,
#c1 .odswidget-date-range-slider .irs--flat .irs-single,
#c1 .odswidget-date-range-slider .irs--flat .irs-handle.state_hover>i:first-child,
#c1 .odswidget-date-range-slider .irs--flat .irs-handle:hover>i:first-child {
    background-color: blue;
}

#c1 .odswidget-date-range-slider .irs--flat .irs-from:before,
#c1 .odswidget-date-range-slider .irs--flat .irs-to:before,
#c1 .odswidget-date-range-slider .irs--flat .irs-single:before {
    border-top-color: blue;
}

#c2 .odswidget-date-range-slider .irs--flat .irs-handle>i:first-child,
#c2 .odswidget-date-range-slider .irs--flat .irs-bar,
#c2 .odswidget-date-range-slider .irs--flat .irs-from,
#c2 .odswidget-date-range-slider .irs--flat .irs-to,
#c2 .odswidget-date-range-slider .irs--flat .irs-single,
#c2 .odswidget-date-range-slider .irs--flat .irs-handle.state_hover>i:first-child,
#c2 .odswidget-date-range-slider .irs--flat .irs-handle:hover>i:first-child {
    background-color: green;
}

#c2 .odswidget-date-range-slider .irs--flat .irs-from:before,
#c2 .odswidget-date-range-slider .irs--flat .irs-to:before,
#c2 .odswidget-date-range-slider .irs--flat .irs-single:before {
    border-top-color: green;
}

#c3 .odswidget-date-range-slider .irs--flat .irs-handle>i:first-child,
#c3 .odswidget-date-range-slider .irs--flat .irs-bar,
#c3 .odswidget-date-range-slider .irs--flat .irs-from,
#c3 .odswidget-date-range-slider .irs--flat .irs-to,
#c3 .odswidget-date-range-slider .irs--flat .irs-single,
#c3 .odswidget-date-range-slider .irs--flat .irs-handle.state_hover>i:first-child,
#c3 .odswidget-date-range-slider .irs--flat .irs-handle:hover>i:first-child {
    background-color: red;
}

#c3 .odswidget-date-range-slider .irs--flat .irs-from:before,
#c3 .odswidget-date-range-slider .irs--flat .irs-to:before,
#c3 .odswidget-date-range-slider .irs--flat .irs-single:before {
    border-top-color: red;
}
