<div class="row">
    <div class="col-md-4">
        <a href="#" class="access-card">
            <div class="access-card-img"
                 style="background-image: url('https://userclub.opendatasoft.com/assets/theme_image/access-cards.jpg')">
                <h3 class="access-card-pretitle">Éphémère</h3>
            </div>
            <div class="access-card-content">
                <h2 class="access-card-title">Opération jardins éphémères</h2>
                <h4 class="access-card-subtitle">Liste et carte des jardins éphémères 2021</h4>
                <p>Politique publique : Biodiversité</p>
                <p>Type : Catalogue</p>
                <p>Support : Portail opendata</p>
                <p>Développement : Direction du Numérique - Orléans Métropole</p>
                <div class="access-card-button">
                    <div class="access-card-button-content">
                        Accédez
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>