/* See more button
   ========================================================================== */
.button-see-more {
    display: inline-block;
    margin-bottom: 1rem;
    padding: 1rem 3rem;
    border: none;
    border-radius: 20px;
    text-align: center;
    transition: all .2s;
    outline: none;
    background-color: #FFE548; /* Button background color */
}
.button-see-more:hover {
    background-color: #ffd900; /* Button background color on mouse hover */
}
