<div class="container">
    <h4>A simple grid <code>grid-cols-3</code></h4>
    <div class="grid-cols-3">
        <div class="box dark">I'm a cell</div>
        <div class="box dark">I'm a cell</div>
        <div class="box dark">I'm a cell</div>
        <div class="box dark">I'm a cell</div>
        <div class="box dark">I'm a cell</div>
        <div class="box dark">I'm a cell</div>
    </div>

    <h4>Responsive grid</h4>
    <p>Think mobile first ! Set the mobile grid, then add wider screen behaviors.</p>
    <div class="grid-2 md:grid-4">
        <div class="box dark">I'm a cell in a responsive grid !</div>
        <div class="box dark">I'm a cell in a responsive grid !</div>
        <div class="box dark">I'm a cell in a responsive grid !</div>
        <div class="box dark">I'm a cell in a responsive grid !</div>
    </div>
</div>