<!-- V2.1 :
    - Add ods-select and multiple choice option for filters
    - Add clear all filter button when one filter is applied
    - responsive display for filters and date button
    - KPI default value to 0 when no data/results to display
  -->
<!-- V2.0 :
  - add a date field that display a date range slider
  - download link knows support files hosted on ODS
  - dynamic title / descriptiton / access source link from the context
-->

<!-- IMPORTANT ******** MUST READ !

    In the following settings declaration :

    A common error is forget to escape (protect) apostrophe with a leading backslash
    As apostrophes are used to declare values of variable it will break the settings

    Ex:
    wrongVariable = 'I'll be freed from apostrophes'
    correctVariable = 'I\'ll be freed from apostrophes'
-->

<!-- SETTINGS START HERE -->
<div class="container"
