<ods-dataset-context context="ctx"
                     ctx-dataset="shanghai-world-university-ranking@public"
                     ctx-domain="public">
    <h3>
        Ods-date-range-slider by year
    </h3>
    <div id="c1">
        <ods-date-range-slider context="ctx"

                               date-format="YYYY"

                               initial-from="2010/01/01"
                               initial-to="2015/01/01"

                               precision="year"

                               date-field="year"

                               start-bound="'2005/01/01'"
                               end-bound="'2018/01/01'">
        </ods-date-range-slider>

        <div id="c2">
            <ods-date-range-slider context="ctx"

                                   date-format="YYYY"

                                   initial-from="2010/01/01"
                                   initial-to="2015/01/01"

                                   precision="year"

                                   date-field="year"

                                   start-bound="'2005/01/01'"
                                   end-bound="'2018/01/01'">
            </ods-date-range-slider>
        </div>

        <div id="c3">
            <ods-date-range-slider context="ctx"

                                   date-format="YYYY"

                                   initial-from="2010/01/01"
                                   initial-to="2015/01/01"

                                   precision="year"

                                   date-field="year"

                                   start-bound="'2005/01/01'"
                                   end-bound="'2018/01/01'">
            </ods-date-range-slider>
        </div>
    </div>
</ods-dataset-context>
