/* Tab Pills
   ========================================================================== */
.tab-pills .ods-simple-tabs-nav-link {
    padding: 0.5rem 1.5rem;
    border-bottom: 0;
    border-radius: 30px;
    background-color: transparent;
}
.tab-pills .ods-simple-tabs-nav-link:hover {
    color: var(--links);
}
.tab-pills .ods-simple-tabs-nav-link-active {
    background-color: var(--links);
}
.tab-pills .ods-simple-tabs-nav-link-active,
.tab-pills .ods-simple-tabs-nav-link-active:hover {
    color: #FFFFFF;
}
      