<div class="row">
    <p>
        Adaptive height
    </p>
</div>
<div class="row">
    <div class="col-md-4">
        <!-- KPI box component -->
        <div class="kpi-card">
            <i class="kpi-icon fa fa-gitlab" aria-hidden="true"></i>
            <p class="kpi-title">
                5,983
            </p>
            <p class="kpi-description">
                Dignissim suspendisse in est ante in nibh nisl tincidunt eget
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <!-- KPI box component -->
        <div class="kpi-card">
            <i class="kpi-icon fa fa-houzz" aria-hidden="true"></i>
            <p class="kpi-title">
                18.3k
            </p>
            <p class="kpi-description">
                Quam vulputate dignissim suspendisse in est ante in nibh. Faucibus nisl tincidunt eget nullam non nisi est sit amet
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <!-- KPI box component -->
        <div class="kpi-card">
            <i class="kpi-icon fa fa-houzz" aria-hidden="true"></i>
            <p class="kpi-title">
                8.3k
            </p>
            <p class="kpi-description">
                Quam vulputate
            </p>
        </div>
    </div>
</div>


<div class="row">
    <p>
        Same height
    </p>
</div>
<div class="row row-equal-height">
    <div class="col-md-4">
        <!-- KPI box component -->
        <div class="kpi-card">
            <i class="kpi-icon fa fa-gitlab" aria-hidden="true"></i>
            <p class="kpi-title">
                5,983
            </p>
            <p class="kpi-description">
                Dignissim suspendisse in est ante in nibh nisl tincidunt eget
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <!-- KPI box component -->
        <div class="kpi-card">
            <i class="kpi-icon fa fa-houzz" aria-hidden="true"></i>
            <p class="kpi-title">
                18.3k
            </p>
            <p class="kpi-description">
                Quam vulputate dignissim suspendisse in est ante in nibh. Faucibus nisl tincidunt eget nullam non nisi est sit amet
            </p>
        </div>
    </div>
    <div class="col-md-4">
        <!-- KPI box component -->
        <div class="kpi-card">
            <i class="kpi-icon fa fa-houzz" aria-hidden="true"></i>
            <p class="kpi-title">
                8.3k
            </p>
            <p class="kpi-description">
                Quam vulputate
            </p>
        </div>
    </div>
</div>
