<!-- V1 :
  - listing generator adapted to custom view :
      - no more context to init, and using existing one "ctx"
  - filters are hidden in /explore/datasets/ view, but visible in embed mode
-->


<!-- IMPORTANT ******** MUST READ !

    In the following settings declaration :

    A common error is forget to escape (protect) apostrophe with a leading backslash
    As apostrophes are used to declare values of variable it will break the settings

    Ex:
    wrongVariable = 'I'll be freed from apostrophes'
    correctVariable = 'I\'ll be freed from apostrophes'
-->

<!-- SETTINGS START HERE -->
<div class="container custom-view-generator"


