<div class="container">
    <h4>The problem ❌</h4>
    <div class="grid-12">
        <div class="cell-6 sm:cell-3">
            <div class="box red">
                <h3>Secondary content</h3>
                <p>1'234 $</p>
            </div>
        </div>
        <div class="cell-6 sm:cell-3">
            <div class="box green">
                <h3>MAIN Content</h3>
                <img src="https://userclub.opendatasoft.com/assets/theme_image/pie-chart.svg" />
            </div>
        </div>
        <div class="cell-6 sm:cell-3">
            <div class="box green">
                <h3>MAIN Content</h3>
                <img src="https://userclub.opendatasoft.com/assets/theme_image/pie-chart.svg" />
            </div>
        </div>
        <div class="cell-6 sm:cell-3">
            <div class="box red">
                <h3>Secondary content</h3>
                <p>1'234 $</p>
            </div>
        </div>
    </div>

    <hr/>

    <h4>The solution ✅</h4>
    <div class="grid-12">
        <div class="cell-6 sm:cell-3 sm:cell-order-2">
            <div class="box green">
                <h3>MAIN Content</h3>
                <img src="https://userclub.opendatasoft.com/assets/theme_image/pie-chart.svg" />
            </div>
        </div>
        <div class="cell-6 sm:cell-3 sm:cell-order-3">
            <div class="box green">
                <h3>MAIN Content</h3>
                <img src="https://userclub.opendatasoft.com/assets/theme_image/pie-chart.svg" />
            </div>
        </div>
        <div class="cell-6 sm:cell-3 sm:cell-order-1">
            <div class="box red">
                <h3>Secondary content</h3>
                <p>1'234 $</p>
            </div>
        </div>
        <div class="cell-6 sm:cell-3 sm:cell-order-4">
            <div class="box red">
                <h3>Secondary content</h3>
                <p>1'234 $</p>
            </div>
        </div>
    </div>
</div>