<!-- V2.1 :
    - Add ods-select and multiple choice option for filters
    - Add clear all filter button when one filter is applied
    - responsive display for filters and date button
    - KPI default value to 0 when no data/results to display
  -->
<!-- V2.0 :
  - add a date field that display a date range slider
  - download link knows support files hosted on ODS
  - dynamic title / descriptiton / access source link from the context
-->

<div class="container"
