<div class="container">
    <h4>gap-1</h4>
    <div class="grid-2 gap-1">
        <div class="box dark">1</div>
        <div class="box dark">2</div>
        <div class="box dark">3</div>
        <div class="box dark">4</div>
    </div>

    <h4>gap-10</h4>
    <div class="grid-2 gap-y-10">
        <div class="box dark">1</div>
        <div class="box dark">2</div>
        <div class="box dark">3</div>
        <div class="box dark">4</div>
    </div>

</div>