/* PAGE LAYOUT AND OVERALL STYLE */
.title {
    text-align: center;
}
.title h2 {
    font-size: 2.3em;
    font-weight: 300;
}
.title p {
    margin-top: 20px;
    font-size: 1.3em;
    font-weight: 300;
}
.chart-space {
    padding-bottom: 60px;
    padding-top: 60px;
}
.chart-bottom-line {
    border-bottom: 1px solid #cecece7d;
}
.chart-inner-block {
    box-shadow: 9px 17px 60px #afafaf;
    padding: 50px 50px 20px 27px;
}
.chart-text {
    padding-left: 50px;
    padding-right: 40px;
}
.chart-text h2 {
    font-size: 2em;
    font-weight: 300;
}
.chart-text p {
    font-size: 1.3em;
    font-weight: 300;
}
.chart-text__announcement {
    text-align: center;
}
.chart-text__announcement p {
    border-left: none;
    padding-left: inherit;
}
.chart-text__announcement a {
    font-size: 1.4em;
    text-transform: uppercase;
}
/* TEXT AND SPECIFIC ELEMENT STYLE */
.chart-inner-block__kpi {
    margin: 50px;
    padding: 25px 50px;
    text-align: center;
    font-size: 2.5em;
    font-weight: 500;
}
.chart-inner-block__kpi-legend {
    font-size: 0.4em;
    font-weight: 100;
}
.access {
    text-transform: uppercase;
}
.code {
    color: #e26f27;
    font-family: monospace;
    font-size: 0.95em;
}
.brand {
    font-weight: 400;
}
/* CHART GLOBAL OVERRIDE */
rect.highcharts-background {
    fill: transparent !important;
}
/* SPECIFIC WIDGET OVERRIDE */
#chart1 text.highcharts-axis-title {
    display: none;
}
#table1 {
    padding: 0px;
}
      
