<!-- V2.1 :
    - Add ods-select and multiple choice option for filters
    - Add clear all filter button when one filter is applied
    - Add documentation
  -->

<!-- IMPORTANT ******** MUST READ !

    In the following settings declaration :

    A common error is forget to escape (protect) commas with a leading backslash
    As commas are used to declare values of variable it will break the settings

    Ex:
    wrongVariable = 'I'll be freed from commas'
    correctVariable = 'I\'ll be freed from commas'
-->
