<ods-dataset-context context="">
    <!-- Header banner. To change the image, go in the CSS tab and search for the .page-header class -->
    <div class="page-header">
        <h1 class="page-title">
            -- Page title --
        </h1>
    </div>
    <!-- Page subtitle -->
    <div class="container">
        <div class="page-subtitle">
            -- Short description of what the page is about -- 
        </div>
    </div>
    <!-- Some KPIs-->
    <section>
        <div class="container">
            <!-- Insert your aggregation widget code in the "three-columns" <div> below -->
            <div class="three-columns">
                <div class="kpi-box">
                    <i class="kpi-icon fa fa-gitlab" aria-hidden="true"></i>
                    <h3 class="kpi-value">
                        --
                    </h3>
                    <p class="kpi-description">
                        -- KPI description goes here --
                    </p>
                </div>
                <div  class="kpi-box">
                    <i class="kpi-icon fa fa-houzz" aria-hidden="true"></i>
                    <h3 class="kpi-value"> 
                        --
                    </h3>
                    <p class="kpi-description">
                        -- KPI description goes here --
                    </p>
                </div>
                <div class="kpi-box">
                    <i class="kpi-icon fa fa-houzz"aria-hidden="true" ></i>
                    <h3 class="kpi-value"> 
                        --
                    </h3>
                    <p class="kpi-description">
                        -- KPI description goes here --
                    </p>
                </div>
            </div>
        </div>
    </section>
    <div class="container">
        <!-- Section 1-->
        <section class="page-section">
            <h2 class="section-title">
                -- Section title --
            </h2>
            <div class="row">
                <div class="col-md-6">
                    <!-- Remove this placeholder and replace it with the visualization of your choice (map, chart, table, etc.) -->
                    <div class="placeholder"></div>
                    <!-- Always provide a link to the dataset for users to dig into the data if they want to-->
                    <div class="small-link">
                        <a href="#">-- link to source --</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <p>
                        -- Description of the visualisation that is being presented -- 
                    </p>
                </div>
            </div>
        </section>
        <!-- End of the first section -->
        <!-- Section 2 -->
        <section class="page-section">
            <h2 class="section-title">
                -- Section title --
            </h2>
            <div class="row">
                <div class="col-md-6">
                    <p>
                        -- Description of the visualisation that is being presented --
                    </p>
                </div>
                <div class="col-md-6">
                    <!-- Remove this placeholder and replace it with the visualization of your choice (map, chart, table, etc.) -->
                    <div class="placeholder"></div>
                    <div class="small-link">
                        <a href="#">-- link to source --</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Section 3 -->
        <section class="page-section">
            <h2 class="section-title">
                -- Section title --
            </h2>
            <div class="row">
                <div class="col-md-8">
                    <div class="placeholder"></div>
                    <div class="small-link">
                        <a href="#">-- link to source --</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <p>
                        -- Description of the visualisation that is being presented --
                    </p>
                </div>
            </div>
        </section>
    </div>
</ods-dataset-context>
      