/* Sticky Summary
========================================================================== */
.sticky-summary-wrapper {
    position: sticky;
    z-index: 10;
    top: 0;
    left: 0;
    background-color: #FFFFFF;
    box-shadow: 0 2px 0 rgba(0,0,0,.2);
}
.sticky-summary {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem;
}
.sticky-summary-data {
    flex: 1 1 auto;
    margin-right: 1rem;
}
.sticky-summary-button {
    color: #FFFFFF;
    background-color: #EC643C;
    border: 1px solid #EC643C;
    font-size: 1rem;
    font-weight: normal;
    padding: .5rem 1rem;
    border-radius: 4px;
    text-decoration: none;
    cursor: pointer;
}
.sticky-summary-button:hover {
    text-decoration: none;
    background-color: #df4516;
    border-color: #df4516;
}
      