.kpi-bloc {
    border: 1px solid;
    padding: 2px;
    margin-bottom: 15px;
    text-align: center;
    height: 130px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}
.kpi-bloc.top3 {
    background-color: #fbd66f6b;
}
.commune {
    font-weight: 100;
    font-size: 1.2em;
    line-height: 20px;
}
.position {
    font-size: 1.1em;
}
.population {
    font-weight: 700;
}
.ratio {
    font-size: 0.9em;
}