<ods-dataset-context context="ushospitals"
                     ushospitals-dataset="us-hospitals"
                     ushospitals-domain="userclub">
    <h3>1 column fixed</h3>
    <ods-table context="ushospitals"
               class="sticky-col-1"
               style="height: 220px;"></ods-table>
</ods-dataset-context>

<ods-dataset-context context="belgiumstatisticaldistricts"
                     belgiumstatisticaldistricts-dataset="belgium-statistical-districts"
                     belgiumstatisticaldistricts-domain="userclub">
    <h3>3 column fixed</h3>
    <ods-table context="belgiumstatisticaldistricts"
               class="sticky-col-3"
               style="height: 220px;"></ods-table>
</ods-dataset-context>