<div class="shared-width-ods-selects">
    <ods-select selected-values="choice"
                options="['objects','things','stuff']"
                placeholder="pick what you want"></ods-select>
    <ods-select selected-values="place"
                options="['car','home']"
                placeholder="pick a place"></ods-select>
    <ods-select selected-values="long"
                options="['2018','2019','2020','2021', 'let see how it behaves with small screens.']"
                placeholder="very long content here, even too long for mobile display"></ods-select>
</div>