/***** Inlined SELECT *****/
.ods-selects {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 20px;
    padding: 10px 0px;
}

.odswidget-select {
    min-width: 200px;
}

/***** Clear filters button *****/

.clear-filters {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 5px;
}

.clear-filters-button {
  background: none;
  border: none;
  color: var(--text);
}

.clear-filters-button:hover {
  opacity: 0.65;
}