.homemadechart__line {
    position: relative;
    width: 100%;
    margin: 5px 0;
}
.homemadechart__line-progressionbar {
    position: absolute;
    background-color: #142e7a;
    color: white;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-radius: 1000px;
    height: 30px;
    padding: 0 10px;
    border: 2px solid #e0e0e0;
}
.homemadechart__line-progressionbar:hover, .homemadechart__line-progressionbar.selected {
    border-color: #142e79;
    font-weight: 600;
}
.homemadechart__line-progressionbackground {
    width: 100%;
    height: 30px;
    background-color: #e0e0e0;
    display: block;
    border-radius: 1000px;
}
.homemadechart__focus {
    position: relative;
    padding: 10px 15px 0px;
}
.homemadechart__focus h4 {
    margin: 0;
}
.homemadechart__focus__close {
    position: absolute;
    right: 20px;
    top: 10px;
    padding: 0px;
    font-size: 1.2em;
}
.homemadechart .odswidget.odswidget-charts {
    height: 250px;
    padding: 20px 30px 0px;
}
