<section>
    <div class="container">
        <div class="heading">
            <h1>Title</h1>
            <p class="subtitle">Sub title</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam atque commodi cupiditate, deserunt
                dolores dolorum ducimus ea fugiat non quidem repellat soluta voluptate voluptatem. Illo illum maxime
                nemo officia velit.</p>
        </div>
        <div class="grid-5 gap-10 my-4.5">
            <div class="sm:cell-2 content-box text align-right">
                <h3>Title</h3>
                <p class="subtitle">Subtitle</p>
                <p>Aligned text on the right</p>
            </div>
            <div class="sm:cell-3 content-box">
                Chart here
            </div>
        </div>
        <div class="heading">
            <h3 class="title">Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam atque commodi cupiditate, deserunt
                dolores dolorum ducimus ea fugiat non quidem repellat soluta voluptate voluptatem. Illo illum maxime
                nemo officia velit.</p>
        </div>
        <div class="grid-5 gap-10 my-4.5">
            <div class="sm:cell-2 sm:cell-order-2 content-box text align-left">
                <h3>Title</h3>
                <p class="subtitle">Subtitle</p>
                <p>Aligned text on the left</p>
            </div>
            <div class="sm:cell-3 sm:cell-order-1 content-box">
                Chart here
            </div>
        </div>
        <div class="heading">
            <h3 class="title">Lorem ipsum dolor sit amet, consectetur adipisicing elit</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam atque commodi cupiditate, deserunt
                dolores dolorum ducimus ea fugiat non quidem repellat soluta voluptate voluptatem. Illo illum maxime
                nemo officia velit.</p>
        </div>
        <div class="grid gap-1 my-4.5">
            <div class="content-box text">
                <h3>Title</h3>
                <p class="subtitle">Subtitle</p>
                <p>Aligned text on the left</p>
            </div>
            <div class="content-box">
                Chart here
            </div>
        </div>
    </div>
</section>