<div class="row row-equal-height">
    <div class="col-md-3 margin-bottom-2">
        <!-- Action card -->
        <a href="#"
           class="action-card">
            <i class="fa fa-map-o action-card-icon" aria-hidden="true"></i>
            <h3 class="action-card-title">
                Create a map
            </h3>
        </a>
    </div>
    <div class="col-md-3 margin-bottom-2">
        <!-- Action card -->
        <a href="#"
           class="action-card">
            <i class="fa fa-bar-chart action-card-icon" aria-hidden="true"></i>
            <h3 class="action-card-title">
                Create a chart
            </h3>
        </a>
    </div>
    <div class="col-md-3 margin-bottom-2">
        <!-- Action card -->
        <a href="#"
           class="action-card">
            <i class="fa fa-cogs action-card-icon" aria-hidden="true"></i>
            <h3 class="action-card-title">
                API
            </h3>
        </a>
    </div>
    <div class="col-md-3 margin-bottom-2">
        <!-- Action card -->
        <a href="#"
           class="action-card">
            <i class="fa fa-book action-card-icon" aria-hidden="true"></i>
            <h3 class="action-card-title">
                Documentation
            </h3>
        </a>
    </div>
</div>
