<div class="container">
    <h4>grid</h4>
    <div class="grid">
        <div class="cell-2 box dark">cell-2</div>
        <div class="box dark">Ø</div>
        <div class="box dark">Ø</div>
        <div class="box dark">Ø</div>
    </div>

    <h4>grid-auto</h4>
    <div class="grid-auto">
        <div class="cell-2 box dark">cell-2</div>
        <div class="box dark">Ø</div>
        <div class="box dark">Ø</div>
        <div class="box dark">Ø</div>
    </div>

    <h4>grid-cols-fit</h4>
    <div class="grid-cols-fit">
        <div class="cell-2 box dark">1 --- --- --- --- --- --- --- --- --- long content</div>
        <div class="box dark">2 --- short content</div>
        <div class="box dark">3</div>
        <div class="box dark">4</div>
    </div>




</div>