<div class="container">
    <h4>KPI Wall</h4>
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="box dark">I'm a KPI, 12/12 on mobile, 6/12 on tablet, 3/12 above !</div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="box dark">I'm a KPI, 12/12 on mobile, 6/12 on tablet, 3/12 above !</div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="box dark">I'm a KPI, 12/12 on mobile, 6/12 on tablet, 3/12 above !</div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="box dark">I'm a KPI, 12/12 on mobile, 6/12 on tablet, 3/12 above !</div>
        </div>
    </div>

    <h4>KPI and it's description</h4>
    <div class="row">
        <div class="col-md-3">
            <div class="box dark">I'm a KPI, centered on mobile, 3/12 above !</div>
        </div>
        <div class="col-md-9">
            <div class="box dark">I'm it's description, 12/12 on mobile, 9/12 above !</div>
        </div>
    </div>

    <h4>Adaptive height</h4>
    <div class="row">
        <div class="col-md-3">
            <div class="box dark">I'm a small KPI !</div>
        </div>
        <div class="col-md-5">
            <div class="row full-height">
                <div class="col-md-12">
                    <div class="box dark">
                        I'm a KPI
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="box dark">
                        I'm a KPI
                    </div>
                </div>
                <div class="col-md-12 no-mb">
                    <div class="box dark">
                        I'm a KPI
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="box dark">
                I'm a tall KPI with a lot of content !
                <br/>
                A
                </br>
                B
                </br>
                C
                </br>
                D
                </br>
                E
                </br>
                F
                </br>
                G
            </div>
        </div>
    </div>
</div>