<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="row full-height">
                <div class="col-md-12">
                    <div class="box white flat">
                        <div class="advanced-kpi">
                            <div class="advanced-kpi--top">
                                <h3 class="title">
                                    Title
                                </h3>
                                <p class="description">
                                    Description
                                </p>
                            </div>
                            <div class="advanced-kpi--middle centered">
                                <p class="value">
                                    1'234 %
                                </p>
                            </div>
                            <div class="advanced-kpi--bottom">
                                <div class="advanced-kpi--bottom-second-stage">
                                    <span class="date">Date</span>
                                    <a class="source"
                                       href="#"
                                       title="Title">
                                        Source <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 no-mb">
                    <div class="box white flat">
                        <div class="advanced-kpi">
                            <div class="advanced-kpi--top">
                                <h3 class="title">
                                    Title
                                </h3>
                                <p class="description">
                                    Description
                                </p>
                            </div>
                            <div class="advanced-kpi--middle centered">
                                <p class="value">
                                    1'234 %
                                </p>
                            </div>
                            <div class="advanced-kpi--bottom">
                                <div class="advanced-kpi--bottom-second-stage">
                                    <span class="date">Date</span>
                                    <a class="source"
                                       href="#"
                                       title="Title">
                                        Source <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="box white flat">
                <div class="advanced-kpi">
                    <div class="advanced-kpi--top">
                        <h3 class="title">
                            Title
                        </h3>
                        <p class="description">
                            Description
                        </p>
                    </div>
                    <div class="advanced-kpi--middle no-bg mb-0">
                        <div class="chart-placeholder"></div>
                    </div>
                    <div class="advanced-kpi--bottom">
                        <div class="advanced-kpi--bottom-second-stage">
                            <span class="date">Date</span>
                            <a class="source"
                               href="#"
                               title="Title">
                                Source <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
