<div class="content-card">
    <div class="row">
        <div class="col-sm-6">
            <!-- Replace this widget with your own visualisation -->
            <ods-dataset-context context="countoursgeographiques"
                                 countoursgeographiques-dataset="contours-geographiques-simplifies-des-nouvelles-regions-metropole"
                                 countoursgeographiques-domain="public"
                                 countoursgeographiques-parameters="{}">
                <ods-map context="countoursgeographiques"
                         scroll-wheel-zoom="false"
                         location="6,47.13742,3.69141"
                         basemap="jawg.streets"></ods-map>
            </ods-dataset-context>
        </div>
        <div class="col-sm-6">
            <h2 class="content-card-title">
                France departments
            </h2>
            <p class="content-card-description">
                Cardano could be many technical analysis since Nexo data mining a fundamental analysis.
            </p>
            <p class="content-card-description">
                Ravencoin generates a amazing fish of lots of market cap, and Waves serves many quick anti-money laundering! Solidity allowed lots of fast peer-to-peer network.
            </p>
            <a href="#"
               class="content-card-link">
                En savoir <i class="fa fa-plus fa-fw" aria-hidden="true"></i>
            </a>
        </div>
    </div>
</div>
