#top10 table {
    width: 100%;
}
#top10 tr th, #top10 tr td {
    padding: 5px;
}
#top10 table td, #top10 table th {
    text-align: center;
}
#top10 tr:nth-child(odd) {
    background-color: #f1f1f1;
}
#top10 tr:nth-child(1) { /* Headers */
    background-color: #142e7a;
    color: white;
}
#top10 tr:nth-child(2) { /* First pos. */
    font-weight: 800;
    font-size: 1.4em;
}
#top10 tr:nth-child(3) { /* Second pos. */
    font-weight: 700;
    font-size: 1.3em;
}
#top10 tr:nth-child(4) { /* Third pos. */
    font-weight: 600;
    font-size: 1.2em;
}
