<div class="ods-selects">
    <p>I want all</p>
    <ods-select selected-values="choice"
                options="['objects','things','stuff']"
                placeholder="pick what you want"></ods-select>
    <p>in your</p>
    <ods-select selected-values="place"
                options="['car','home']"
                placeholder="pick a place"></ods-select>
    <p>since</p>
    <ods-select selected-values="month"
                options="['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']"
                placeholder="month"></ods-select>
    <ods-select selected-values="year"
                options="['2018','2019','2020','2021']"
                placeholder="year"></ods-select>
</div>