<div class="placeholder-content">
    <section class="sticky-content">
        <h2>
            Sticky content is here
        </h2>
    </section>
    <h3 class="placeholder-title">
        Page content is here
    </h3>
</div>
<hr class="placeholder-separator">
<div class="placeholder-content">
    <br>
    <h3 class="placeholder-title">
        Page content is here
    </h3>
    <section class="sticky-content">
        <h2>
            Sticky content is here
        </h2>
    </section>
    <h3 class="placeholder-title">
        More content here
    </h3>
</div>
