main.main--page {
    margin: 0;
    background-color: #FFFFFF;
    line-height: 1.6;
}

.datastory-header {
    margin-top: 40px;
    margin-bottom: 60px;
    max-width: 1000px;
    text-align: center;
}

.datastory-title {
    font-size: 3rem;
    font-weight: normal;
    margin-bottom: 1.5rem;
}

.datastory-tagline {
    font-size: 1.4rem;
    font-style: italic;
    margin-top: 0;
    margin-bottom: 40px;
    font-weight: 300;    
}

.datastory-intro {
    font-size: 1.4rem;
    font-weight: normal;
    text-align: justify;
}

.datastory-body {
    max-width: 750px;
}

.datastory-subtitle {
    font-size: 1.44rem;
    border-left: 3px solid var(--highlight);
    padding-left: 12px;
    font-weight: 400; 
}

.datastory-text {
    font-size: 1.2rem;
    margin-left: 15px;
}
 
.datastory-image {
    margin: 0 auto;
    display: block;
    max-width: 100%;
    height: auto;
}