<div class="container">
    <h4>KPI Wall</h4>
    <div class="grid-4">
        <div class="cell-full sm:cell-2 md:cell-1">
            <div class="box dark">I'm a KPI, 12/12 on mobile, 6/12 on tablet, 3/12 above !</div>
        </div>
        <div class="cell-full sm:cell-2 md:cell-1">
            <div class="box dark">I'm a KPI, 12/12 on mobile, 6/12 on tablet, 3/12 above !</div>
        </div>
        <div class="cell-full sm:cell-2 md:cell-1">
            <div class="box dark">I'm a KPI, 12/12 on mobile, 6/12 on tablet, 3/12 above !</div>
        </div>
        <div class="cell-full sm:cell-2 md:cell-1">
            <div class="box dark">I'm a KPI, 12/12 on mobile, 6/12 on tablet, 3/12 above !</div>
        </div>
    </div>

    <h4>KPI and it's description</h4>
    <div class="grid-12">
        <div class="cell-start-5 cell-end-9 md:cell-3">
            <div class="box dark">I'm a KPI, centered on mobile, 3/12 above !</div>
        </div>
        <div class="md:cell-9">
            <div class="box dark">I'm it's description, 12/12 on mobile, 9/12 above !</div>
        </div>
    </div>

    <h4>Adaptive height</h4>
    <div class="grid-cols-11">
        <div class="cell-3">
            <div class="box dark">I'm a small KPI !</div>
        </div>
        <div class="cell-5">
            <div class="box dark">
                I'm a KPI
            </div>
            <div class="box dark">
                I'm a KPI
            </div>
            <div class="box dark">
                I'm a KPI
            </div>
        </div>
        <div class="cell-3">
            <div class="box dark">
                I'm a tall KPI with a lot of content !
                <br/>
                A
                </br>
                B
                </br>
                C
                </br>
                D
                </br>
                E
                </br>
                F
                </br>
                G
            </div>
        </div>
    </div>
</div>