/* Sticky Content
   ========================================================================== */
.sticky-content {
    position: sticky;
    top: 0;
    z-index: 10;
    background-color: hotpink;
    color: #FFFFFF;
    padding: 3rem 20px;
}
.placeholder-content {
    height: 600px;
    background-color: lightgreen;
}
.placeholder-title {
    margin-top: 1.5rem;
    margin-bottom: 1.5rem;
    padding-left: 20px;
}
.placeholder-separator {
    margin-top: 3rem;
    margin-bottom: 3rem;
}
