.items-row {
    text-align: center; /* center all buttons */
}
.items {
    display: inline-flex; /* Display in line */
    list-style-type: none; /* Remove the list bullet */
}
.item {
    margin: 0 20px; /* give some space left and right */
}
.ods-button {
    font-weight: 500;
}
.ods-button--primary {
    border: solid 1px #1E0C33;
    background-color: #1E0C33;
}
.ods-button--danger {
    border: solid 1px #a94442;
    background-color: #a94442;
}
.chart-title, .hint {
    text-align: center;
    font-style: italic;
    color: darkgrey;
    font-weight: 300;
}
.chart-title b {
    font-weight: 500;
}
tspan.highcharts-text-outline {
    display: none;
}
.spacer {
        margin-bottom: 20px;
    width: 90%;
    border-top: 1px solid rgba(30, 12, 51, 0.53);
    margin-left: auto;
    margin-right: auto;
}
#circle-gauge {
    max-width: 300px;
    margin: auto;
}
#red-gauge .odswidget-gauge__svg-filler {
    stroke: red;
}
#orange-gauge .odswidget-gauge__svg-filler {
    stroke: orange;
}
#green-gauge .odswidget-gauge__svg-filler {
    stroke: green;
}
#red-gauge .odswidget-gauge__value {
    color: red;
}
#orange-gauge .odswidget-gauge__value {
    color: orange;
}
#green-gauge .odswidget-gauge__value {
    color: green;
}

