:root {
    --secondary-color: #142E7B;
}

.access-card-link {
    color: var(--text);
}

.access-card-link:hover {
    text-decoration: none;
}

.access-card {
    border-radius: 10px;
    background-color: #fff;
    height: 100%;
    background-color: var(--boxes-background);
}

.access-card-img {
    background-image: url("https://userclub.opendatasoft.com/assets/theme_image/access-cards.jpg");
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center;
    height: 240px;
}

.access-card-content {
    padding: 20px;
}

.access-card-pretitle {
    text-transform: uppercase;
    color: var(--secondary-color);
    opacity: 0.7;
    font-weight: 400;
    margin: 0px;
    font-size: 12px;
}

.access-card-title {
    font-weight: 400;
    margin: 10px 0px;
    font-size: 22px;
}

.access-card-subtitle {
    font-size: 16px;
    font-weight: 400;
    margin: 0px 0px 10px 0px;
}

.access-card-content p {
    margin: 5px 0px;
}

.access-card-button {
    display: flex;
    justify-content: center;
    padding: 10px 0px;
}

.access-card-button:hover {
    opacity: 0.7;
}

.access-card-button-content {
    background-color: var(--secondary-color);
    text-align: center;
    color: #FFF;
    border-radius: 24px;
    padding: 5px 15px;
}
