<div class="row">
    <div class="col-md-4">
        <!-- Access card (Title + Description + light arrow button + full height image) -->
        <a href="#" class="access-card-link">
            <div class="access-card-bg">
                <div class="access-card">
                    <div class="access-card-img"></div>
                    <div class="access-card-content">
                        <h3 class="access-card-pretitle">Éphémère</h3>
                        <h2 class="access-card-title">Opération jardins éphémères</h2>
                        <h4 class="access-card-subtitle">Liste et carte des jardins éphémères 2021</h4>
                        <p>Politique publique : Biodiversité</p>
                        <p>Type : Catalogue</p>
                        <p>Support : Portail opendata</p>
                        <p>Développement : Direction du Numérique - Orléans Métropole</p>
                    <div class="access-card-button">
                        <div class="access-card-button-content">
                        Accédez
                    </div>
                </div>
                </div>
            </div>
        </a>
    </div>
</div>